name: carrefour
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=2.1
  - numpy>=1.26
  - matplotlib>=3.8
  - seaborn>=0.13
  - jupyter>=1.0
  - ipykernel
  - pyarrow
  - pyyaml
  - umap-learn=0.5.6
  - plotly=5.22.0
  - libgomp
  - scipy
  - ipython
  - pip
  - pip:
    - polars>=1.0
    - torch
    - gensim>=4.3.2
    - hdbscan==0.8.40
    - anthropic
    - python-dotenv
