name: carrefour
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=2.1
  - numpy>=1.26
  - matplotlib>=3.8
  - seaborn>=0.13
  - jupyter>=1.0
  - ipykernel
  - pyarrow
  - gensim
  - umap-learn
  - hdbscan
  - pip
  - pip:
    - polars>=1.0
    - torch
