"""Product-theme patterns for tribe narrative overlays."""

from __future__ import annotations

import re
import unicodedata


STRATEGIC_THEME_PATTERNS: dict[str, list[str]] = {
    "baby": [
        r"\brecien nacido\b",
        r"\btex baby\b",
        r"\bpanal(?:es)?\b",
        r"\bdodot\b",
        r"\bpotito(?:s)?\b",
        r"\bpapilla(?:s)?\b",
        r"\btarrito(?:s)?\b",
        r"\byogolino\b",
        r"\bchupete(?:s)?\b",
        r"\bbiberon(?:es)?\b",
        r"\bhero baby\b",
        r"\bhero recetas caseras\b",
        r"\b(?:toallita|toallitas|champu|gel|colonia|crema|locion|leche|protector solar)\b.*\b(?:bebe|baby)\b",
        r"\b(?:bebe|baby)\b.*\b(?:toallita|toallitas|champu|gel|colonia|crema|locion|panal|panales|potito|papilla|biberon|chupete|alimentacion|infantil)\b",
        r"\bcarrefour baby\b",
        r"\bcuna(?: de viaje| bebe| colecho| madera| plegable)\b",
        r"\bsilla de paseo\b",
    ],
    "baby_food": [
        r"\bpotito(?:s)?\b",
        r"\bpapilla(?:s)?\b",
        r"\btarrito(?:s)?\b",
        r"\byogolino\b",
        r"\bhero baby\b",
        r"\bhero recetas caseras\b",
        r"\b(?:bebe|baby)\b.*\b(?:alimentacion|comida|cereal|fruta|verdura|pure|crema|leche infantil)\b",
    ],
    "baby_care": [
        r"\bpanal(?:es)?\b",
        r"\bdodot\b",
        r"\bchupete(?:s)?\b",
        r"\bbiberon(?:es)?\b",
        r"\b(?:toallita|toallitas|champu|gel|colonia|crema|locion|leche|protector solar)\b.*\b(?:bebe|baby)\b",
        r"\b(?:bebe|baby)\b.*\b(?:toallita|toallitas|champu|gel|colonia|crema|locion|panal|panales|chupete|biberon)\b",
    ],
    "baby_clothing": [
        r"\b(?:bebe|baby|recien nacido|tex baby)\b.*\b(?:body|pijama|camiseta|pantalon|vestido|falda|jersey|chaqueta|calcetin|zapato|zapatilla|abrigo|ranita|pelele)\b",
        r"\b(?:body|pijama|camiseta|pantalon|vestido|falda|jersey|chaqueta|calcetin|zapato|zapatilla|abrigo|ranita|pelele)\b.*\b(?:bebe|baby|recien nacido|tex baby)\b",
    ],
    "baby_girls_clothing": [
        r"\b(?:bebe|baby|recien nacido|tex baby)\b.*\b(?:nina|vestido|falda|leotardo|diadema)\b",
        r"\b(?:nina|vestido|falda|leotardo|diadema)\b.*\b(?:bebe|baby|recien nacido|tex baby)\b",
    ],
    "baby_boys_clothing": [
        r"\b(?:bebe|baby|recien nacido|tex baby)\b.*\b(?:nino|bermuda|polo|camisa)\b",
        r"\b(?:nino|bermuda|polo|camisa)\b.*\b(?:bebe|baby|recien nacido|tex baby)\b",
    ],
    "pet": [
        r"\bmascota(?:s)?\b",
        r"\bpienso\b",
        r"\bperros?\b.*\b(?:humedo|seco|pienso|alimento|comida|snack|lata|tarrina|pouch|collar|cama|juguete|champu|higiene|adult|junior|senior|mini|kg|gr|g)\b",
        r"\b(?:humedo|seco|pienso|alimento|comida|snack|lata|tarrina|pouch|collar|cama|juguete|champu|higiene|kg|gr|g)\b.*\bperros?\b",
        r"\b\d+(?:,\d+)? ?(?:kg|gr|g)\b.*\bperros?\b",
        r"\bgatos?\b.*\b(?:arena|humedo|seco|pienso|alimento|comida|snack|lata|tarrina|pouch|collar|cama|juguete|hierba|adult|junior|senior|kg|gr|g)\b",
        r"\b(?:arena|humedo|seco|pienso|alimento|comida|snack|lata|tarrina|pouch|collar|cama|juguete|hierba|kg|gr|g)\b.*\bgatos?\b",
        r"\b\d+(?:,\d+)? ?(?:kg|gr|g)\b.*\bgatos?\b",
        r"\bgatera\b",
        r"\bfriskies\b",
        r"\bwhiskas\b",
        r"\bpurina\b",
        r"\bpedigree\b",
        r"\bfelix\b",
    ],
    "pet_dog": [
        r"\bperros?\b.*\b(?:pienso|alimento|comida|snack|lata|tarrina|pouch|collar|cama|juguete|champu|higiene|adult|junior|senior|mini|kg|gr|g)\b",
        r"\b(?:pienso|alimento|comida|snack|lata|tarrina|pouch|collar|cama|juguete|champu|higiene)\b.*\bperros?\b",
        r"\bpedigree\b",
        r"\bdentastix\b",
        r"\bultima\b.*\bperro\b",
        r"\bcanin[oa]s?\b",
    ],
    "pet_cat": [
        r"\bgatos?\b.*\b(?:arena|pienso|alimento|comida|snack|lata|tarrina|pouch|collar|cama|juguete|hierba|adult|junior|senior|kg|gr|g)\b",
        r"\b(?:arena|pienso|alimento|comida|snack|lata|tarrina|pouch|collar|cama|juguete|hierba)\b.*\bgatos?\b",
        r"\bgatera\b",
        r"\bwhiskas\b",
        r"\bcat(?:isfaction| chow)\b",
        r"\bsanicat\b",
        r"\bultima\b.*\bgato\b",
        r"\bfelix\b.*\b(?:gato|cat|pouch|salsa|sensations|receta|junior)\b",
    ],
    "organic_bio": [
        r"\bbio\b",
        r"\becologico(?:s|a|as)?\b",
        r"\becologica(?:s)?\b",
        r"\borganico(?:s|a|as)?\b",
        r"\bbiologico(?:s|a|as)?\b",
        r"\bagricultura ecologica\b",
        r"\balgodon ecologico\b",
    ],
    "gluten_free": [r"sin gluten", r"\bsg\b"],
    "lactose_free": [r"sin lactosa", r"lactose free"],
    "protein_fitness": [
        r"\bproteina(?:s)?\b",
        r"\bprotein\b",
        r"\bwhey\b",
        r"\bbarrita(?:s)? prote",
        r"\bcreatina\b",
        r"\bbcaa\b",
        r"\bbebida isotonica\b",
    ],
    "zero_sugar_light": [
        r"\bzero\b",
        r"\b0 ?%",
        r"\bsin azucar(?:es)?\b",
        r"\blight\b",
        r"\bedulcorante\b",
        r"\bstevia\b",
    ],
    "health_wellness": [
        r"\bintegral(?:es)?\b",
        r"\bsalud\b",
        r"\bomega ?3\b",
        r"\bvitamina(?:s)?\b",
        r"\bsin sal\b",
        r"\bbajo en sal\b",
        r"\bcolesterol\b",
        r"\bfibra\b",
        r"\bdesnatad",
        r"\bprobio",
        r"\bdigestiv",
    ],
    "plant_based": [
        r"\bvegano(?:s|a|as)?\b",
        r"\bvegetal(?:es)?\b",
        r"\btofu\b",
        r"\bseitan\b",
        r"\bheura\b",
        r"\bfalafel\b",
        r"\bplant based\b",
        r"\bbebida (?:de )?(?:soja|avena|almendra|arroz|coco)\b",
        r"\bhamburguesa(?:s)? vegetal(?:es)?\b",
        r"\balbondigas vegetal(?:es)?\b",
    ],
    "ready_meals": [
        r"\bplato(?:s)? preparado(?:s)?\b",
        r"\bpreparad",
        r"\bprecocinado(?:s|a|as)?\b",
        r"\blisto para\b",
        r"\bcalentar\b",
        r"\bpizza(?:s)?\b",
        r"\blasana(?:s)?\b",
        r"\bcanelon(?:es)?\b",
        r"\bcroqueta(?:s)?\b",
        r"\bempanado(?:s|a|as)?\b",
        r"\btortilla(?:s)?\b",
        r"\bgazpacho\b",
        r"\bsalmorejo\b",
        r"\bcrema de (?:calabaza|verduras|espinacas|puerros|champi)",
        r"\bsopa(?:s)?\b",
    ],
    "premium_indulgence": [
        r"\bpremium\b",
        r"\bgourmet\b",
        r"\bdelicat",
        r"\bseleccion\b",
        r"\breserva\b",
        r"\bgran reserva\b",
        r"\biberico(?:s|a|as)?\b",
        r"\bfoie\b",
        r"\btrufa(?:s)?\b",
        r"\bbufala\b",
        r"\bdop\b",
        r"\bartesano(?:s|a|as)?\b",
    ],
    "fresh_produce": [
        r"\bfruta(?:s)?\b",
        r"\bverdura(?:s)?\b",
        r"\bhortaliza(?:s)?\b",
        r"\blechuga(?:s)?\b",
        r"\btomate(?:s)?\b",
        r"\bpatata(?:s)?\b",
        r"\bcebolla(?:s)?\b",
        r"\bzanahoria(?:s)?\b",
        r"\bcalabacin(?:es)?\b",
        r"\bpimiento(?:s)?\b",
        r"\bberenjena(?:s)?\b",
        r"\bmanzana(?:s)?\b",
        r"\bplatano(?:s)?\b",
        r"\bnaranja(?:s)?\b",
        r"\bmelon(?:es)?\b",
        r"\bsandia(?:s)?\b",
        r"\bpera(?:s)?\b",
        r"\buva(?:s)?\b",
        r"\bkiwi(?:s)?\b",
        r"\baguacate(?:s)?\b",
        r"\bensalada(?:s)?\b",
    ],
    "meat_charcuterie": [
        r"\bpollo\b",
        r"\bpavo\b",
        r"\bcerdo\b",
        r"\bternera\b",
        r"\bvacuno\b",
        r"\bbuey\b",
        r"\bcordero\b",
        r"\bconejo\b",
        r"\bjamon\b",
        r"^(?!.*\bpatatas fritas\b).*\bchorizo\b",
        r"\bsalchich",
        r"\blomo\b",
        r"\bpanceta\b",
        r"\bmorcilla\b",
        r"\bfuet\b",
        r"\blonganiza\b",
        r"\bhamburguesa(?:s)?\b",
    ],
    "halal": [
        r"\bhalal\b",
    ],
    "seafood": [
        r"\bpescado(?:s)?\b",
        r"\batun\b",
        r"\bsalmon\b",
        r"\bbacalao\b",
        r"\bmerluza\b",
        r"\bsardina(?:s)?\b",
        r"\bboqueron(?:es)?\b",
        r"\banchoa(?:s)?\b",
        r"\bgamba(?:s)?\b",
        r"\blangost",
        r"\bcalamar(?:es)?\b",
        r"\bpulpo\b",
        r"\bmejillon(?:es)?\b",
        r"\balmeja(?:s)?\b",
        r"\bsepia\b",
        r"\brape\b",
    ],
    "dairy_eggs": [
        r"\bleche\b",
        r"\byogur(?:t|es)?\b",
        r"\bqueso(?:s)?\b",
        r"\bmantequilla\b",
        r"\bnata\b",
        r"\bkefir\b",
        r"\bcuajada\b",
        r"\bflan(?:es)?\b",
        r"\bhuevo(?:s)?\b",
        r"\bmozzarella\b",
        r"\bcamembert\b",
        r"\bedam\b",
        r"\bfeta\b",
        r"\bparmesano\b",
    ],
    "bakery_breakfast": [
        r"\bpan\b",
        r"\bbarra\b",
        r"\bbaguette(?:s)?\b",
        r"\bbolleria\b",
        r"\bbollo(?:s)?\b",
        r"\bcroissant(?:s)?\b",
        r"\bmagdalena(?:s)?\b",
        r"\bnapolitana(?:s)?\b",
        r"\bcereal(?:es)?\b",
        r"\bmuesli\b",
        r"\btostada(?:s)?\b",
        r"\bgalleta(?:s)?\b",
        r"\btortita(?:s)?\b",
        r"\bbizcocho(?:s)?\b",
    ],
    "pantry_staples": [
        r"\braceite\b",
        r"\boliva\b",
        r"\bgirasol\b",
        r"\barroz\b",
        r"\bpasta\b",
        r"\bspaghetti\b",
        r"\bmacarron(?:es)?\b",
        r"\blegumbre(?:s)?\b",
        r"\bgarbanzo(?:s)?\b",
        r"\blenteja(?:s)?\b",
        r"\bjudia(?:s)?\b",
        r"\bharina\b",
        r"\bazucar\b",
        r"\bsal\b",
        r"\bvinagre\b",
        r"\btomate frito\b",
        r"\bconserva(?:s)?\b",
        r"\bcaldo(?:s)?\b",
        r"\bsalsa(?:s)?\b",
        r"\bmayonesa\b",
        r"\bketchup\b",
        r"\bmostaza\b",
        r"\bmiel\b",
        r"\bmermelada(?:s)?\b",
    ],
    "world_foods_asian": [
        r"\bsalsa (?:de )?soja\b",
        r"\bteriyaki\b",
        r"\bwasabi\b",
        r"\bsushi\b",
        r"\bramen\b",
        r"\bnoodle(?:s)?\b",
        r"\byakisoba\b",
        r"\bwok\b",
        r"\bthai\b",
        r"\btempura\b",
        r"\bgyoza(?:s)?\b",
        r"\bsriracha\b",
        r"\bkimchi\b",
        r"\bmiso\b",
    ],
    "world_foods_mexican": [
        r"\btaco(?:s)?\b",
        r"\bfajita(?:s)?\b",
        r"\bnacho(?:s)?\b",
        r"\bguacamole\b",
        r"\bjalapeno(?:s)?\b",
        r"\bburrito(?:s)?\b",
        r"\btortilla(?:s)? mexicana(?:s)?\b",
        r"\bold el paso\b",
    ],
    "world_foods_middle_eastern": [
        r"\bhummus\b",
        r"\bfalafel\b",
        r"\bcous ?cous\b",
        r"\bcuscus\b",
        r"\bkebab\b",
        r"\btahini\b",
    ],
    "world_foods_latin": [
        r"\barepa(?:s)?\b",
        r"\byuca\b",
        r"\byerba mate\b",
        r"\bmate cocido\b",
        r"\bdulce de leche\b",
        r"\bempanada(?:s)? argentina(?:s)?\b",
    ],
    "snacks_sweets": [
        r"\bpatatas fritas\b",
        r"\bsnack(?:s)?\b",
        r"\baperitivo(?:s)?\b",
        r"\bchocolate(?:s)?\b",
        r"\bbombon(?:es)?\b",
        r"\bturron(?:es)?\b",
        r"\bcaramelo(?:s)?\b",
        r"\bgominola(?:s)?\b",
        r"\bchicle(?:s)?\b",
        r"\bpalomitas\b",
        r"\bfrutos secos\b",
        r"\balmendra(?:s)?\b",
        r"\bpistacho(?:s)?\b",
        r"\bcacahuete(?:s)?\b",
    ],
    "beverages_soft": [
        r"\bagua (?:mineral|natural|con gas|sin gas|sabor|de coco|tonica)\b",
        r"\bagua\b.*\b(?:botella|pack|garrafa|litro|litros|\d+(?:,\d+)? ?l|\d+ ?ml|pet)\b",
        r"\b(?:botella|pack|garrafa)\b.*\bagua\b",
        r"\brefresco(?:s)?\b",
        r"\bcola\b",
        r"\bzumo(?:s)?\b",
        r"\bnectar(?:es)?\b",
        r"\bbebida(?:s)?\b",
        r"\btonica\b",
        r"\bisotonic",
        r"\bkombucha\b",
        r"\bhorchata\b",
        r"\bbatido(?:s)?\b",
        r"\bgaseosa\b",
    ],
    "coffee_tea": [
        r"\bcafe (?:molido|grano|capsula|soluble|latte|caffe|descafeinado|mezcla|natural|espresso|colombia|fortaleza|lor|marcilla|nescafe|medalla|kilimanjaro)\b",
        r"\b(?:capsula|molido|grano|molinillo|bebida) de cafe\b",
        r"\bcaffe\b",
        r"\bcapsula(?:s)? (?:cafe|nespresso|dolce|tassimo|lor|marcilla)\b",
        r"\b(?:nespresso|dolce gusto|tassimo|lor|marcilla)\b.*\bcapsula(?:s)?\b",
        r"\bnespresso\b",
        r"\bdolce gusto\b",
        r"\btassimo\b",
        r"\bte (?:verde|negro|rojo|blanco|limon|menta|matcha|chai|frio|clasico|desteinado|rooibos|hornimans|pickw)",
        r"\binfusion(?:es)?\b",
        r"\bmanzanilla\b",
        r"\btila\b",
        r"\brooibos\b",
        r"\bmatcha\b",
    ],
    "alcohol": [
        r"(?<!vinagre de )\bvino(?:s)?\b",
        r"\bcerveza(?:s)?\b",
        r"\bsidra\b",
        r"\bcava\b",
        r"\bchampagne\b",
        r"\bwhisky\b",
        r"\bginebra\b",
        r"\bron\b",
        r"\bvodka\b",
        r"\blicor(?:es)?\b",
        r"\bvermut\b",
        r"\bbrandy\b",
    ],
    "alcohol_free": [
        r"\bsin alcohol\b",
        r"\b0[,\.]0\b",
        r"\b0 ?% ?(?:alcohol|alc)\b",
        r"\bcerveza(?:s)?\b.*\b0 ?%\b",
        r"\bcerveza(?:s)?\b.*\bzero zero\b",
        r"\bzero zero\b",
        r"\bfree damm\b",
        r"\bbuckler\b.*\b0 ?%\b",
    ],
    "frozen_ice_cream": [
        r"\bcongelad",
        r"\bultracongelad",
        r"\bhelado(?:s)?\b",
        r"\bsorbete(?:s)?\b",
        r"\bhielo\b",
    ],
    "home_cleaning": [
        r"\bdetergente(?:s)?\b",
        r"\bsuavizante(?:s)?\b",
        r"\blavavajillas\b.*\b(?:pastilla|capsula|gel|finish|fairy|quantum|classic|detergente)",
        r"\b(?:pastilla|capsula|gel|finish|fairy|quantum|classic|detergente)\b.*\blavavajillas\b",
        r"\blimpiador(?:es)?\b",
        r"\blejia\b",
        r"\bambientador(?:es)?\b",
        r"\bmopa(?:s)?\b",
        r"\bfregasuelos\b",
        r"\bbolsa(?:s)? basura\b",
        r"\bpapel higienico\b",
        r"\bservilleta(?:s)?\b",
        r"\brollos\b",
        r"\bwc\b",
        r"\bdesinfectante(?:s)?\b",
        r"\bquitagrasas\b",
        r"\babrillantador\b",
    ],
    "personal_care_beauty": [
        r"\bchampu\b",
        r"\bshampoo\b",
        r"\bgel (?:ducha|bano|hidroalcoholico|limpiador)\b",
        r"\bdentifrico(?:s)?\b",
        r"\bpasta dental\b",
        r"\bcolgate\b",
        r"\bdesodorante(?:s)?\b",
        r"\bcrema (?:facial|corporal|manos|hidratante|reafirmante|anti|noche|dia)\b",
        r"\bmaquillaje\b",
        r"\brimmel\b",
        r"\beyeliner\b",
        r"\bpintalabios\b",
        r"\btinte(?:s)?\b",
        r"\bafeitado\b",
        r"\bcompresa(?:s)?\b",
        r"\btampon(?:es)?\b",
        r"\bprotege slip\b",
        r"\bcolonia\b",
        r"\bperfume(?:s)?\b",
        r"\bfotoprotector\b",
    ],
    "apparel_textile": [
        r"\bcamiseta(?:s)?\b",
        r"\bpantalon(?:es)?\b",
        r"\bpijama(?:s)?\b",
        r"\bsujetador(?:es)?\b",
        r"\bcalcetin(?:es)?\b",
        r"\bbraga(?:s)?\b",
        r"\bslip\b",
        r"\btanga(?:s)?\b",
        r"\bzapat",
        r"\bbotin(?:es)?\b",
        r"\bsudadera(?:s)?\b",
        r"\bjersey(?:s)?\b",
        r"\bchaqueta(?:s)?\b",
        r"\bvestido(?:s)?\b",
        r"\bfalda(?:s)?\b",
        r"\bbermuda(?:s)?\b",
        r"\bshort(?:s)?\b",
        r"\bbikini(?:s)?\b",
        r"\bbanador(?:es)?\b",
        r"\bpanty\b",
        r"\bleggins\b",
        r"\btex\b",
    ],
    "books_toys": [
        r"\blibro(?:s)?\b",
        r"\bcuento(?:s)?\b",
        r"\blectura(?:s)?\b",
        r"\beditorial\b",
        r"\banaya\b",
        r"\bsusaeta\b",
        r"\bpanini books\b",
        r"\bjuguete(?:s)?\b",
        r"\bmuneca(?:s)?\b",
        r"\blego\b",
        r"\bpuzzle(?:s)?\b",
        r"\bplaymobil\b",
        r"\bbarbie\b",
        r"\bpeluche(?:s)?\b",
        r"\bjuego(?:s)? mesa\b",
        r"\bcolorear\b",
        r"\bpegatina(?:s)?\b",
    ],
    "kids_general": [
        r"\bninos\b",
        r"\binfantil(?:es)?\b",
        r"\bjuguete(?:s)?\b",
        r"\blego\b",
        r"\bplaymobil\b",
        r"\bpaw patrol\b",
        r"\bcuento(?:s)?\b",
    ],
    "kids_girls": [
        r"\bnina(?:s)?\b",
        r"\bbarbie\b",
        r"\bmuneca(?:s)?\b",
    ],
    "kids_boys": [
        r"\bnino\b",
        r"\bhot wheels\b",
        r"\bspiderman\b",
    ],
    "home_kitchen": [
        r"\bvajilla(?:s)?\b",
        r"\bvaso(?:s)?\b",
        r"\bplato(?:s)?\b",
        r"\bcopa(?:s)?\b",
        r"\bsarten(?:es)?\b",
        r"\bolla(?:s)?\b",
        r"\bcacerola(?:s)?\b",
        r"\bcubierto(?:s)?\b",
        r"\btaza(?:s)?\b",
        r"\bmolde(?:s)?\b",
        r"\bbandeja(?:s)?\b",
        r"\bmesa(?:s)?\b",
        r"\bsilla(?:s)?\b",
        r"\bcojin(?:es)?\b",
        r"\bsabana(?:s)?\b",
        r"\bedredon(?:es)?\b",
        r"\bfunda(?:s)?\b",
        r"\btoalla(?:s)?\b",
        r"\bcortina(?:s)?\b",
        r"\bvela(?:s)?\b",
        r"\bjarron(?:es)?\b",
        r"\bmacetero(?:s)?\b",
        r"\balfombra(?:s)?\b",
        r"\blampara(?:s)?\b",
        r"\bbombilla(?:s)?\b",
        r"\bpila(?:s)?\b",
        r"\btendedero(?:s)?\b",
        r"\bpercha(?:s)?\b",
    ],
    "electronics_appliances": [
        r"\btelevisor(?:es)?\b",
        r"\btelefono movil\b",
        r"\bsmartphone(?:s)?\b",
        r"\bauricular(?:es)?\b",
        r"\bfrigorifico(?:s)?\b",
        r"\blavadora(?:s)?\b",
        r"\blavavajillas\b.*\b(?:aeg|balay|bosch|candy|beko|siemens|whirlpool|integrable|instalacion|inox|servicios|cm)\b",
        r"\bmicroondas\b",
        r"\bcafetera(?:s)?\b",
        r"\bbatidora(?:s)?\b",
        r"\brobot de cocina\b",
        r"\bplancha(?:s)?\b",
        r"\bsecador(?:es)?\b",
        r"\baspirador(?:es)?\b",
        r"\btablet(?:s)?\b",
        r"\bportatil(?:es)?\b",
        r"\bordenador (?:portatil|sobremesa|gaming|aio)\b",
        r"\bconsola(?:s)?\b",
        r"\bimpresora(?:s)?\b",
        r"\bcamara(?:s)?\b",
        r"\baltavoz(?:es)?\b",
        r"\bmonitor(?:es)?\b",
        r"\bhdmi\b",
        r"\busb\b",
    ],
    "diy_auto_garden": [
        r"\bneumatico(?:s)?\b",
        r"\braceite motor\b",
        r"\blimpiaparabrisas\b",
        r"\bfiltro (?:aceite|gasolina)\b",
        r"\bcoche(?:s)?\b",
        r"\bmoto(?:s)?\b",
        r"\bbicicleta(?:s)?\b",
        r"\bherramienta(?:s)?\b",
        r"\batornillador(?:es)?\b",
        r"\btaladro(?:s)?\b",
        r"\btornillo(?:s)?\b",
        r"\bpintura(?:s)?\b",
        r"\bbarniz\b",
        r"\badhesivo(?:s)?\b",
        r"\bcinta aislante\b",
        r"\bfertilizante(?:s)?\b",
        r"\bsustrato(?:s)?\b",
        r"\binsecticida(?:s)?\b",
        r"\bbarbacoa(?:s)?\b",
        r"\bcesped\b",
        r"\bjardin\b",
    ],
    "fuel_convenience": [
        r"\bgasolina\b",
        r"\bdiesel\b",
        r"\bgasoleo\b",
        r"\bcarburante(?:s)?\b",
    ],
    "seasonal_celebration": [
        r"\bnavidad\b",
        r"\bhalloween\b",
        r"\bcumple(?:anos)?\b",
        r"\bpapa noel\b",
        r"\breyes magos\b",
        r"\bdisfraz(?:es)?\b",
        r"\bdecoracion\b",
        r"\btarta\b.*\b(?:cumple|madre|padre|navidad)\b",
    ],
}


_COMPILED_THEME_PATTERNS: dict[str, re.Pattern[str]] = {
    theme: re.compile("|".join(f"(?:{pattern})" for pattern in patterns))
    for theme, patterns in STRATEGIC_THEME_PATTERNS.items()
}


def _repair_mojibake(text: str) -> str:
    """Repair common UTF-8 text that was decoded as Latin-1."""

    try:
        return text.encode("latin1").decode("utf-8")
    except UnicodeError:
        return text


def normalize_product_text(description: str | None) -> str:
    """Return lowercase ASCII text suitable for product keyword matching."""

    text = _repair_mojibake(description or "").casefold()
    text = unicodedata.normalize("NFKD", text)
    text = text.encode("ascii", "ignore").decode("ascii")
    return re.sub(r"\s+", " ", text).strip()


def detect_product_themes(description: str | None) -> list[str]:
    text = normalize_product_text(description)
    themes = []
    for theme, pattern in _COMPILED_THEME_PATTERNS.items():
        if pattern.search(text):
            themes.append(theme)
    if "baby" in themes:
        ingredient_or_format_themes = {
            "dairy_eggs",
            "fresh_produce",
            "meat_charcuterie",
            "pantry_staples",
            "ready_meals",
        }
        themes = [theme for theme in themes if theme not in ingredient_or_format_themes]
    return themes


__all__ = ["STRATEGIC_THEME_PATTERNS", "detect_product_themes", "normalize_product_text"]
